// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClwEAgV-J7qwy8ziZkmtvXH_CvAJ1pRcI',
    appId: '1:474216978889:web:75ca659a060d9e20e07018',
    messagingSenderId: '474216978889',
    projectId: 'final-henry-b849e',
    authDomain: 'final-henry-b849e.firebaseapp.com',
    storageBucket: 'final-henry-b849e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjEG97iHWqKOL-NA_QALVvLA66vBZLZdk',
    appId: '1:474216978889:android:1e21351b57ad101ee07018',
    messagingSenderId: '474216978889',
    projectId: 'final-henry-b849e',
    storageBucket: 'final-henry-b849e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASkJYeXYVU3eeoSyR36mLemUerEGgEMn0',
    appId: '1:474216978889:ios:6e681b6dda58fbf1e07018',
    messagingSenderId: '474216978889',
    projectId: 'final-henry-b849e',
    storageBucket: 'final-henry-b849e.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASkJYeXYVU3eeoSyR36mLemUerEGgEMn0',
    appId: '1:474216978889:ios:6e681b6dda58fbf1e07018',
    messagingSenderId: '474216978889',
    projectId: 'final-henry-b849e',
    storageBucket: 'final-henry-b849e.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );
}
