// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUJo4ygLXmcqIvUey_JJIC4sS7dpxNVG0',
    appId: '1:157702746971:web:726b12f901a7a5dda1607e',
    messagingSenderId: '157702746971',
    projectId: 'threads-henry',
    authDomain: 'threads-henry.firebaseapp.com',
    storageBucket: 'threads-henry.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzBgQclZlNAU8TLqW5ACQ2_15bnel6rIc',
    appId: '1:157702746971:android:f3437e1af8eb2f7fa1607e',
    messagingSenderId: '157702746971',
    projectId: 'threads-henry',
    storageBucket: 'threads-henry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA30LK7wnXvcW4Wbbn8z7ltjD6Z1QfPUx4',
    appId: '1:157702746971:ios:968d23d49bd018bba1607e',
    messagingSenderId: '157702746971',
    projectId: 'threads-henry',
    storageBucket: 'threads-henry.appspot.com',
    iosBundleId: 'com.example.threads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA30LK7wnXvcW4Wbbn8z7ltjD6Z1QfPUx4',
    appId: '1:157702746971:ios:968d23d49bd018bba1607e',
    messagingSenderId: '157702746971',
    projectId: 'threads-henry',
    storageBucket: 'threads-henry.appspot.com',
    iosBundleId: 'com.example.threads',
  );
}
